### ISSUE TITLE
Image does not appear in Documents

### ISSUE THREAD

**Issue by alexsafayan** [elfnor/blender_auto_save_on_render#1]
When a image is done rendering, it doesn't auto save to documents.  Can anyone help?

**Comment by elfnor** [comment]
Where is the original blend file saved?

The image and the copy of the blend file will be saved in a sub folder of this location called auto_saves. If you select sub folder another folder will be created underneath auto_saves with the same name as the original blend file.

**Comment by alexsafayan** [comment]
The original blend file is saved to the desktop.

**Comment by elfnor** [comment]
Then you should have a folder \Desktop\auto_saves with a blend file and png file inside it. I just tried it on a windows machine and that's what I got. If you want these in a folder under Documents you need to save the original blend file to the Documents folder.

Can you see the extra checkboxes  in the Render Panel as shown in the readme?

**Comment by alexsafayan** [comment]
Thank you so much!  It worked ;)
